name: Development

on:
  workflow_dispatch:
       inputs:
         dir:
            description: "Path to subdirectory to scan"
            type: string
            default: ""
         summary:
            description: "Generate job summary"
            type: boolean
            default: false 
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source codebase"
        uses: actions/checkout@v3
      - name: Count TODOs
        uses: ./